version: '3.3'

services:
  jupyter:
    build:
      context: .
    user: root
    ports:
      - '8888:8888'
    environment:
      - GRANT_SUDO=yes
    platform: linux/amd64
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER}
        target: /home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
